default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  host: localhost
  password: postgres

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Academy_development

test:
  <<: *default
  database: Academy_test

production:
  <<: *default
  database: Academy_production
  username: Academy
  password: <%= ENV["ACADEMY_DATABASE_PASSWORD"] %>
